### ISSUE TITLE
Runtime error when use the docker image in the flow

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/executor-text-paddle#4]
# Reproduce

flow.py

```python
import click
@click.command()
@click.argument('path', default='.')
@click.option('--verbose', '-v', is_flag=True, help='Enables verbose mode.')
def cli(path, verbose):
    from jina import Flow
    flow = Flow().add(uses=path)
    with flow:
        flow.block()  # block the current process
if __name__ == '__main__':
    cli()
```

execute command

`python3 flow.py jinahub+docker://cjdseojc`

# Error info

```
❯ python3 flow.py jinahub+docker://cjdseojc
        gateway@3445[I]:input tcp://0.0.0.0:54415 (ROUTER_BIND) output None (DEALER_CONNECT) control over ipc:///var/folders/34/htlgtx8j5rg8q0llpwflr_v40000gn/T/tmph9oz_4fw (PAIR_BIND)
        gateway@3445[S]:GRPCRuntime is listening at: 0.0.0.0:54417
           pod0@3444[I]:will use Docker image: jinahub/cjdseojc:v0
           pod0@3444[I]:will use Docker image: jinahub/cjdseojc:v0
           pod0@3444[I]:JINA@ 1[I]:
           pod0@3444[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
           pod0@3444[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
           pod0@3444[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
           pod0@3444[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
           pod0@3444[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
           pod0@3444[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
           pod0@3444[I]:MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
           pod0@3444[I]:NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
           pod0@3444[I]:KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           pod0@3444[I]:
           pod0@3444[I]:▶️  /usr/local/bin/jina executor --uses config.yml --name pod0 --workspace /private/tmp --identity 52f992a8-3103-49d7-b3f6-ba5bd787ba94 --workspace-id 3ce3b92e-e52e-4fca-bc0d-cdd333d0c410 --port-ctrl 54405 --port-in 54406 --port-out 54407 --socket-in ROUTER_BIND --socket-out DEALER_CONNECT --num-part 1 --dynamic-routing-out --dynamic-routing-in --port-expose 54408 --upload-files --noblock-on-start
           pod0@3444[I]:🔧️                            cli = executor
           pod0@3444[I]:ctrl-with-ipc = False
           pod0@3444[I]:daemon = False
           pod0@3444[I]:docker-kwargs = None
           pod0@3444[I]:dynamic-routing = True
           pod0@3444[I]:🔧️             dynamic-routing-in = True
           pod0@3444[I]:🔧️            dynamic-routing-out = True
           pod0@3444[I]:entrypoint = None
           pod0@3444[I]:env = None
           pod0@3444[I]:expose-public = False
           pod0@3444[I]:external = False
           pod0@3444[I]:host = 0.0.0.0
           pod0@3444[I]:host-in = 0.0.0.0
           pod0@3444[I]:host-out = 0.0.0.0
           pod0@3444[I]:🔧️                       identity = 52f992a8-3103-49d7-b3f6-ba5bd7
           pod0@3444[I]:log-config = /usr/local/lib/python3.7/site-
           pod0@3444[I]:memory-hwm = -1
           pod0@3444[I]:🔧️                           name = pod0
           pod0@3444[I]:🔧️               noblock-on-start = True
           pod0@3444[I]:🔧️                       num-part = 1
           pod0@3444[I]:on-error-strategy = IGNORE
           pod0@3444[I]:parallel = 1
           pod0@3444[I]:pea-id = 0
           pod0@3444[I]:pea-role = SINGLETON
           pod0@3444[I]:peas-hosts = None
           pod0@3444[I]:pod-role = None
           pod0@3444[I]:polling = ANY
           pod0@3444[I]:🔧️                      port-ctrl = 54405
           pod0@3444[I]:🔧️                    port-expose = 54408
           pod0@3444[I]:🔧️                        port-in = 54406
           pod0@3444[I]:🔧️                       port-out = 54407
           pod0@3444[I]:proxy = False
           pod0@3444[I]:pull-latest = False
           pod0@3444[I]:py-modules = None
           pod0@3444[I]:quiet = False
           pod0@3444[I]:quiet-error = False
           pod0@3444[I]:quiet-remote-logs = False
           pod0@3444[I]:replicas = 1
           pod0@3444[I]:runtime-backend = PROCESS
           pod0@3444[I]:runtime-cls = ZEDRuntime
           pod0@3444[I]:scheduling = LOAD_BALANCE
           pod0@3444[I]:🔧️                      socket-in = ROUTER_BIND
           pod0@3444[I]:🔧️                     socket-out = DEALER_CONNECT
           pod0@3444[I]:ssh-keyfile = None
           pod0@3444[I]:ssh-password = None
           pod0@3444[I]:ssh-server = None
           pod0@3444[I]:timeout-ctrl = 5000
           pod0@3444[I]:timeout-ready = 600000
           pod0@3444[I]:🔧️                   upload-files = []
           pod0@3444[I]:🔧️                           uses = config.yml
           pod0@3444[I]:uses-after = None
           pod0@3444[I]:uses-before = None
           pod0@3444[I]:uses-internal = BaseExecutor
           pod0@3444[I]:volumes = None
           pod0@3444[I]:🔧️                      workspace = /private/tmp
           pod0@3444[I]:🔧️                   workspace-id = 3ce3b92e-e52e-4fca-bc0d-cdd333
           pod0@3444[I]:
           pod0@3444[I]:pod0@19[I]:input tcp://0.0.0.0:54406 (ROUTER_BIND) output None (DEALER_CONNECT) control over tcp://0.0.0.0:54405 (PAIR_BIND)
           pod0@3444[I]:pod0@19[C]:can not load the executor from config.yml
           pod0@3444[I]:pod0@19[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
           pod0@3444[I]:add "--quiet-error" to suppress the exception details
           pod0@3444[I]:Traceback (most recent call last):
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 148, in _path_import
           pod0@3444[I]:spec.loader.exec_module(module)
           pod0@3444[I]:File "<frozen importlib._bootstrap_external>", line 728, in exec_module
           pod0@3444[I]:File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
           pod0@3444[I]:File "/workspace/text_paddle.py", line 7, in <module>
           pod0@3444[I]:import paddlehub as hub
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/paddlehub/__init__.py", line 18, in <module>
           pod0@3444[I]:import paddle
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 26, in <module>
           pod0@3444[I]:from .fluid import monkey_patch_variable
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
           pod0@3444[I]:from . import framework
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
           pod0@3444[I]:from . import core
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 369, in <module>
           pod0@3444[I]:raise e
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 316, in <module>
           pod0@3444[I]:from .core_noavx import *
           pod0@3444[I]:ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
           pod0@3444[I]:
           pod0@3444[I]:The above exception was the direct cause of the following exception:
           pod0@3444[I]:
           pod0@3444[I]:Traceback (most recent call last):
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 81, in _load_executor
           pod0@3444[I]:runtime_args=vars(self.args),
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/jaml/__init__.py", line 521, in load_config
           pod0@3444[I]:extra_search_paths=(os.path.dirname(s_path),) if s_path else None,
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/jaml/helper.py", line 243, in load_py_modules
           pod0@3444[I]:PathImporter.add_modules(*mod)
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 118, in add_modules
           pod0@3444[I]:module = PathImporter._path_import(p)
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 150, in _path_import
           pod0@3444[I]:raise ImportError(f'can not import module from {absolute_path}') from ex
           pod0@3444[I]:ImportError: can not import module from /workspace/text_paddle.py
           pod0@3444[I]:
           pod0@3444[I]:The above exception was the direct cause of the following exception:
           pod0@3444[I]:
           pod0@3444[I]:Traceback (most recent call last):
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 131, in run
           pod0@3444[I]:runtime = self._build_runtime()
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 118, in _build_runtime
           pod0@3444[I]:return self.runtime_cls(self.args, ctrl_addr=ctrl_addr)
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 54, in __init__
           pod0@3444[I]:self._load_executor()
           pod0@3444[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 94, in _load_executor
           pod0@3444[I]:raise ExecutorFailToLoad from ex
           pod0@3444[I]:jina.excepts.ExecutorFailToLoad
           pod0@3444[I]:WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
           pod0@3444[I]:Error: AVX is not support on your machine, but you have installed paddlepaddle without no_avx core, you should reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/mkl/stable/noavx.html or https://paddlepaddle.org.cn/whl/openblas/stable/noavx.html
           pod0@3444[I]:pod0@ 1[S]:terminated
           pod0@3444[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/peapods/peas/__init__.py", line 153, in run
    runtime = self._build_runtime()
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/peapods/peas/__init__.py", line 140, in _build_runtime
    return self.runtime_cls(self.args, ctrl_addr=ctrl_addr)
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/peapods/runtimes/container/__init__.py", line 29, in __init__
    raise Exception(
Exception: the container fails to start, check the arguments or entrypoint
           pod0@3427[S]:terminated
           Flow@3427[E]:pod0:<jina.peapods.pods.Pod object at 0x126a180a0> can not be started due to RuntimeFailToStart(), Flow is aborted
        gateway@3445[I]:#sent: 0 #recv: 0 sent_size: 0 Bytes recv_size: 0 Bytes
        gateway@3427[S]:terminated
           Flow@3427[S]:flow is closed and all resources are released, current build level is EMPTY
           Flow@3427[S]:flow is closed and all resources are released, current build level is EMPTY
Traceback (most recent call last):
  File "/private/tmp/flow.py", line 11, in <module>
    cli()
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/private/tmp/flow.py", line 8, in cli
    with flow:
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/flow/base.py", line 911, in __enter__
    return self.start()
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/flow/base.py", line 958, in start
    v.wait_start_success()
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/peapods/pods/__init__.py", line 513, in wait_start_success
    p.wait_start_success()
  File "/Users/miaozhaofeng/Documents/jina/jina/jina/peapods/peas/__init__.py", line 215, in wait_start_success
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by mapleeit** [comment]
It's a m1 silicon specific problem. We can ignore this for now.
